### ISSUE TITLE
objectClass=groupOfNames?

### ISSUE THREAD

**Issue by jacobblock** [rbw0/authzync#11]
Hi,

Your script was very helpful. I ran into one snag and that was the use of objectClass=group in query.py. I am not an LDAP expert by any means, but I thought objectClass=groupOfNames was a more common objectClass to go by. Something to consider.

Thanks!

**Comment by rbw0** [comment]
Hello!

What type of LDAP directory are you using?
Perhaps we should make this configurable?

Anyway - good to hear you find it useful. And sorry for late reply, I'm on vacation.

Regards,
Robert

**Comment by jacobblock** [comment]
No worries, hope it is nice! I'm using FreeIPA which uses [389 DS](http://directory.fedoraproject.org/). I have now seen "groupOfUniqueNames", "groupOfNames" and "group", so in general it is just LDAP schema dependent. I would probably suggest exposing the full filter string in the config structure, with a default value of '(objectClass=group)' as it currently is.

Best,
Jacob

**Comment by rbw0** [comment]
Group search_filter is now configurable.
See https://raw.githubusercontent.com/rbw0/authzync/master/examples/authzync.json for an example.

Thanks for suggesting this.

/Robert
